### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by ThibautGery** [Floby/node-bunyan-blackhole#1]
Your project is not up to date with bunyan dependencies, I got this error.  I had to fix the version number of bunyan.

npm ERR! peerinvalid The package bunyan does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer bunyan-blackhole@1.0.1 wants bunyan@~1.3.4

Could you update ? 

Thanks

**Comment by rdy** [comment]
There is an annoying message that was fixed in bunyan 1.4 which would be great to have in the black hole logger. Could you update the dependency on bunyan to the latest?

**Comment by rdy** [comment]
Could you publish the new npm module when you have the chance?

**Comment by Floby** [comment]
Oh right, pushing soon. Sorry

**Comment by Floby** [comment]
published as 1.1.1 !
